// BUILD 121 - Pub Trivia Season Two: bigger hand-written packs. Zero cost, no network,
// no rate limit. Negative ids never collide with OpenTDB. Answers are shuffled at draw time.
import type { LocalCategory, LocalQuestion } from './trivia-local';

const q = (question: string, correct: string, a: string, b: string, c: string): LocalQuestion => ({ question, correct, wrong: [a, b, c] });

export const SEASON_TWO_CATEGORIES: LocalCategory[] = [
  { id: -5, name: '🧪 Brainbox' },
  { id: -6, name: '🍕 Kitchen Table' },
  { id: -7, name: '🌍 Wide World' },
  { id: -8, name: '🎵 Jukebox' },
  { id: -9, name: '🏟️ Sporty' },
  { id: -10, name: '📜 Time Machine' },
];

export const SEASON_TWO_QUESTIONS: Record<number, LocalQuestion[]> = {
  [-5]: [
    q('What is the chemical symbol for gold?', 'Au', 'Go', 'Gd', 'Ag'),
    q('Which planet is known as the Red Planet?', 'Mars', 'Venus', 'Jupiter', 'Mercury'),
    q('How many legs does a spider have?', '8', '6', '10', '12'),
    q('What gas do plants take in from the air?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Helium'),
    q('What is the hardest natural substance on Earth?', 'Diamond', 'Gold', 'Iron', 'Quartz'),
    q('Which is the largest planet in our solar system?', 'Jupiter', 'Saturn', 'Neptune', 'Earth'),
    q('What is the largest mammal on Earth?', 'The blue whale', 'The elephant', 'The giraffe', 'The great white shark'),
    q('Water is made of hydrogen and what?', 'Oxygen', 'Carbon', 'Nitrogen', 'Helium'),
    q('How many bones does an adult human have?', '206', '106', '306', '412'),
    q('What force keeps us stuck to the ground?', 'Gravity', 'Magnetism', 'Friction', 'Inertia'),
    q('Which blood cells carry oxygen around the body?', 'Red blood cells', 'White blood cells', 'Platelets', 'Plasma cells'),
    q('What is the closest star to Earth?', 'The Sun', 'Proxima Centauri', 'Sirius', 'The North Star'),
    q('A baby kangaroo is called a...', 'Joey', 'Cub', 'Pup', 'Kit'),
    q('What do bees collect from flowers to make honey?', 'Nectar', 'Pollen dust only', 'Sap', 'Dew'),
  ],
  [-6]: [
    q('Which country invented pizza?', 'Italy', 'Greece', 'France', 'Spain'),
    q('Guacamole is mainly made from which fruit?', 'Avocado', 'Lime', 'Tomato', 'Mango'),
    q('Which grain is sushi rice?', 'Short-grain rice', 'Barley', 'Couscous', 'Wild rice'),
    q('What is the main ingredient of hummus?', 'Chickpeas', 'Lentils', 'Black beans', 'Peanuts'),
    q('What type of pastry is a classic croissant made from?', 'Laminated, buttery dough', 'Choux pastry', 'Shortcrust', 'Filo'),
    q('Which spice gives paella its golden colour?', 'Saffron', 'Paprika', 'Cumin', 'Cinnamon'),
    q('What is a baby cow called?', 'A calf', 'A kid', 'A foal', 'A lamb'),
    q('Haggis is traditionally eaten in which country?', 'Scotland', 'Wales', 'Ireland', 'England'),
    q('Which cheese is traditionally used on a Greek salad?', 'Feta', 'Cheddar', 'Brie', 'Gouda'),
    q('Tofu is made from which plant?', 'Soybeans', 'Rice', 'Wheat', 'Corn'),
    q('What do you call cooking food gently in water just below boiling?', 'Simmering', 'Searing', 'Flambe', 'Braising'),
    q('Which nut is the main ingredient of marzipan?', 'Almond', 'Cashew', 'Walnut', 'Pistachio'),
    q('A Yorkshire pudding is usually served with what?', 'Roast beef', 'Fish and chips', 'Curry', 'Pancakes only'),
  ],
  [-7]: [
    q('What is the capital of France?', 'Paris', 'Lyon', 'Marseille', 'Nice'),
    q('Which is the longest river in Africa?', 'The Nile', 'The Congo', 'The Niger', 'The Zambezi'),
    q('Which ocean is the largest?', 'The Pacific', 'The Atlantic', 'The Indian', 'The Arctic'),
    q('Mount Everest sits on the border of Nepal and which country?', 'China (Tibet)', 'India only', 'Bhutan', 'Pakistan'),
    q('What is the capital of Australia?', 'Canberra', 'Sydney', 'Melbourne', 'Perth'),
    q('Which country has the most people living in it?', 'India', 'USA', 'Indonesia', 'Brazil'),
    q('Which desert is the largest hot desert in the world?', 'The Sahara', 'The Gobi', 'The Kalahari', 'The Arabian'),
    q('In which country would you find the city of Kyoto?', 'Japan', 'China', 'South Korea', 'Thailand'),
    q('Which continent is the country of Egypt mostly in?', 'Africa', 'Asia', 'Europe', 'South America'),
    q('What is the capital of Canada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'),
    q('Which country is shaped like a boot?', 'Italy', 'Portugal', 'Greece', 'Croatia'),
    q('What is the smallest country in the world by area?', 'Vatican City', 'Monaco', 'San Marino', 'Liechtenstein'),
    q('Which city is known as the Big Apple?', 'New York', 'Los Angeles', 'Chicago', 'Boston'),
    q('The Amazon rainforest is mostly in which country?', 'Brazil', 'Peru', 'Colombia', 'Argentina'),
  ],
  [-8]: [
    q('Which band had a hit with "Bohemian Rhapsody"?', 'Queen', 'The Rolling Stones', 'Led Zeppelin', 'Pink Floyd'),
    q('How many strings does a standard guitar have?', '6', '4', '5', '8'),
    q('Which singer is known as the Queen of Pop?', 'Madonna', 'Whitney Houston', 'Cher', 'Adele'),
    q('The Beatles came from which English city?', 'Liverpool', 'Manchester', 'London', 'Birmingham'),
    q('What instrument has 88 keys?', 'Piano', 'Organ', 'Accordion', 'Harpsichord'),
    q('Which artist released the album "21" in 2011?', 'Adele', 'Amy Winehouse', 'Duffy', 'Lily Allen'),
    q('Who composed "The Four Seasons"?', 'Vivaldi', 'Mozart', 'Bach', 'Beethoven'),
    q('Which band sang "Wonderwall"?', 'Oasis', 'Blur', 'Pulp', 'The Verve'),
    q('What do you call a group of four singers?', 'A quartet', 'A trio', 'A quintet', 'A duet'),
    q('Which instrument does a drummer play?', 'Percussion kit', 'Brass', 'Woodwind', 'Strings'),
    q('Which singer had a 2020 hit called "Blinding Lights"?', 'The Weeknd', 'Drake', 'Post Malone', 'Bruno Mars'),
    q('ABBA come from which country?', 'Sweden', 'Norway', 'Denmark', 'Finland'),
    q('Which music festival takes place on a farm in Somerset?', 'Glastonbury', 'Reading', 'Download', 'Latitude'),
    q('Elvis Presley was nicknamed the King of what?', 'Rock and Roll', 'Pop', 'Country', 'Soul'),
  ],
  [-9]: [
    q('How many players are on the pitch for one football team?', '11', '9', '10', '12'),
    q('Which sport is played at Wimbledon?', 'Tennis', 'Golf', 'Cricket', 'Squash'),
    q('How many rings are on the Olympic flag?', '5', '4', '6', '7'),
    q('In which sport would you score a try?', 'Rugby', 'Football', 'Hockey', 'Baseball'),
    q('Which country hosted the 2012 Summer Olympics?', 'The United Kingdom', 'China', 'Brazil', 'Greece'),
    q('How many points is a touchdown worth in American football?', '6', '3', '7', '5'),
    q('In golf, what is one stroke under par called?', 'A birdie', 'An eagle', 'A bogey', 'An albatross'),
    q('Which sport uses a shuttlecock?', 'Badminton', 'Tennis', 'Squash', 'Table tennis'),
    q('How long is a marathon, roughly?', '26.2 miles', '20 miles', '30 miles', '13.1 miles'),
    q('Which country has won the most football World Cups?', 'Brazil', 'Germany', 'Argentina', 'Italy'),
    q('What colour jersey does the Tour de France race leader wear?', 'Yellow', 'Green', 'Red', 'White'),
    q('How many players are in a basketball team on court?', '5', '6', '7', '4'),
    q('In cricket, what is it called when a batter is out for no runs?', 'A duck', 'A golden hen', 'A zero point', 'A blank'),
  ],
  [-10]: [
    q('In which year did World War Two end?', '1945', '1939', '1918', '1950'),
    q('Who was the first person to walk on the Moon?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'Alan Shepard'),
    q('Which ancient civilisation built the pyramids at Giza?', 'The Egyptians', 'The Romans', 'The Greeks', 'The Mayans'),
    q('Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Botticelli'),
    q('The Great Fire of London happened in which year?', '1666', '1566', '1766', '1066'),
    q('Which wall fell in 1989, symbolising the end of the Cold War division of Germany?', 'The Berlin Wall', 'The Great Wall', 'Hadrian\'s Wall', 'The Western Wall'),
    q('Which ship famously sank on its maiden voyage in 1912?', 'The Titanic', 'The Lusitania', 'The Mayflower', 'The Britannic'),
    q('Who was the first President of the United States?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams'),
    q('The Battle of Hastings took place in which year?', '1066', '1215', '1415', '1588'),
    q('Which empire was ruled by Julius Caesar?', 'The Roman Empire', 'The Greek Empire', 'The Ottoman Empire', 'The Persian Empire'),
    q('Which explorer is credited with reaching the Americas in 1492?', 'Christopher Columbus', 'Vasco da Gama', 'Ferdinand Magellan', 'Marco Polo'),
    q('Which queen reigned for 63 years until 1901?', 'Queen Victoria', 'Elizabeth I', 'Queen Anne', 'Mary I'),
    q('Who invented the telephone, according to the first patent?', 'Alexander Graham Bell', 'Thomas Edison', 'Nikola Tesla', 'Guglielmo Marconi'),
  ],
  // Extra shelves for the original four house categories.
  [-1]: [
    q('Which piece is worth the most points in standard chess scoring?', 'The queen', 'The rook', 'The king', 'The bishop'),
    q('What is the name for a draw where the player to move has no legal move but is not in check?', 'Stalemate', 'Checkmate', 'Zugzwang', 'Perpetual check'),
    q('Which two pieces swap places in a castling move?', 'King and rook', 'King and queen', 'Queen and rook', 'Bishop and knight'),
    q('Which piece is the only one that can jump over others?', 'The knight', 'The bishop', 'The queen', 'The rook'),
    q('What colour moves first in chess?', 'White', 'Black', 'Whoever rolls highest', 'Red'),
    q('A pawn capturing a neighbouring pawn that just moved two squares is called...', 'En passant', 'Castling', 'Promotion', 'Fianchetto'),
    q('What is the name of the opening that begins 1. e4 e5 2. Nf3 Nc6 3. Bb5?', 'The Ruy Lopez', 'The Sicilian', 'The French', 'The Queen\'s Gambit'),
    q('How many squares does a king move at a time?', 'One', 'Two', 'As many as it likes', 'Three'),
  ],
  [-2]: [
    q('What is a "shandy" mixed from?', 'Beer and lemonade', 'Beer and whisky', 'Cider and vodka', 'Wine and cola'),
    q('A pint in the UK is how many fluid ounces?', '20', '16', '24', '12'),
    q('Which game is played with a dartboard divided into 20 numbered sections?', 'Darts', 'Skittles', 'Bar billiards', 'Shove ha\'penny'),
    q('What is the traditional name for the person who runs a pub?', 'The landlord or landlady', 'The maitre d\'', 'The sommelier', 'The barista'),
    q('Which fruit is used to make cider?', 'Apples', 'Pears only', 'Grapes', 'Plums'),
    q('Which snack is traditionally pork scratchings made from?', 'Pork rind', 'Potato', 'Beef', 'Cheese'),
    q('What is the term for the last orders bell call in a British pub?', 'Time, gentlemen, please', 'Closing time, folks', 'Final pour', 'Drinks up'),
  ],
  [-3]: [
    q('Which film features a shark terrorising a beach town?', 'Jaws', 'Deep Blue Sea', 'The Meg', 'Orca'),
    q('Who directed the film "Jurassic Park"?', 'Steven Spielberg', 'James Cameron', 'George Lucas', 'Ridley Scott'),
    q('What is the name of the toy cowboy in "Toy Story"?', 'Woody', 'Buzz', 'Rex', 'Slinky'),
    q('Which film series features a wizard school called Hogwarts?', 'Harry Potter', 'The Hobbit', 'Narnia', 'Percy Jackson'),
    q('Which actor played Jack in "Titanic"?', 'Leonardo DiCaprio', 'Brad Pitt', 'Tom Cruise', 'Matt Damon'),
    q('In "The Lion King", what is the name of Simba\'s father?', 'Mufasa', 'Scar', 'Rafiki', 'Zazu'),
    q('Which 1977 film begins with "A long time ago in a galaxy far, far away"?', 'Star Wars', 'Star Trek', 'Alien', 'Dune'),
    q('What colour is the pill Neo takes to see the truth in "The Matrix"?', 'Red', 'Blue', 'Green', 'White'),
  ],
  [-4]: [
    q('What is the capital of Wales?', 'Cardiff', 'Swansea', 'Newport', 'Wrexham'),
    q('Which famous clock tower stands beside the Houses of Parliament?', 'Elizabeth Tower (Big Ben)', 'Clock Tower of Westminster Abbey', 'Tower of London', 'Tower Bridge'),
    q('Which city is home to the Cavern Club?', 'Liverpool', 'Leeds', 'Bristol', 'Newcastle'),
    q('What is the longest river in the UK?', 'The Severn', 'The Thames', 'The Trent', 'The Tay'),
    q('What is the highest mountain in England?', 'Scafell Pike', 'Snowdon', 'Ben Nevis', 'Helvellyn'),
    q('Which university city is famous for punting on the River Cam?', 'Cambridge', 'Oxford', 'Durham', 'Bath'),
    q('Which monarch lived at Buckingham Palace for most of her reign, ending in 2022?', 'Queen Elizabeth II', 'Queen Victoria', 'Queen Anne', 'Queen Mary'),
  ],
};
