"use client";
import {useMemo,useState} from "react";
import {motion,AnimatePresence} from "framer-motion";
import Link from "next/link";
const P="#ff2bd6",G="#34d399",Y="#facc15";
const DAYS=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const BANDS=["6-9","9-12","12-15","15-18","18-21","21-00","00-03"]; // time of day
// simulated historical yield (GBP/hr) per day x band, seeded not random
const Y0=[[22,18,16,20,34,30,12],[21,17,15,19,33,31,13],[23,18,17,21,35,33,14],[24,19,18,22,38,36,15],[26,21,19,25,44,52,26],[18,22,24,30,48,58,34],[16,20,22,24,36,30,10]];
const APP_SHARE=0.62; // simulated app vs meter split
const ZONES=[{n:"Heathrow T5",y:41,why:"Morning long-hauls"},{n:"King's Cross",y:34,why:"Commuter rail"},{n:"Soho / Theatreland",y:52,why:"Show out 22:30"},{n:"Canary Wharf",y:31,why:"Dinners out"},{n:"Paddington",y:29,why:"Airport express"}];
const BADGES=[{e:"🎓",n:"The Knowledge Master",d:"50 rides with zero sat-nav reroutes",p:41,t:50},{e:"🚌",n:"Bus Lane Navigator",d:"500 min saved for riders",p:386,t:500},{e:"🌟",n:"Five-Star Streak",d:"12 five-star rides in a row",p:9,t:12},{e:"♿",n:"Ramp Hero",d:"25 step-free rides",p:18,t:25},{e:"🦉",n:"Night Owl",d:"20 late-night rides",p:20,t:20}];
const COMPS=[{t:"Knew a shortcut I never would have found",c:14},{t:"Smooth and calm driving",c:9},{t:"Made our evening",c:5},{t:"Patient with the ramp",c:3}];
const REVIEWS=[{n:"Testa",s:5,t:"Dave took the bus lane down Whitehall and got us there 6 minutes early. Legend.",tip:4},{n:"Testb",s:5,t:"So patient helping my mum with the chair. Thank you.",tip:5},{n:"Testa",s:5,t:"Best tour of London I have had in a cab.",tip:0}];
const DEALS=[{e:"⚡",n:"VoltLane Rapid Charging",d:"Cab-only bays, 0.4 mi away",o:"28p/kWh, 20% off peak",g:"from-cyan-900 to-blue-950",a:"#22d3ee"},{e:"🫧",n:"Gleam & Go Valet Wash",d:"Camden, 0.9 mi",o:"Free interior valet every 4th wash",g:"from-emerald-900 to-teal-950",a:G},{e:"📹",n:"NightEye Dashcam",d:"Fitted on site, 1.3 mi",o:"£60 off, fitting free",g:"from-fuchsia-900 to-purple-950",a:P},{e:"🔑",n:"TX Club Leasing",d:"Zero-deposit LEVC TX lease",o:"Fixed £189/wk, servicing included",g:"from-amber-900 to-yellow-950",a:Y}];
const col=(v:number)=>`rgba(255,43,214,${Math.min(1,v/60)*0.9+0.08})`;
function Burst({kind,onDone}:{kind:number;onDone:()=>void}){
 const parts=Array.from({length:28},(_,i)=>({a:i/28*Math.PI*2,d:90+(i%5)*28,c:[P,G,Y][i%3]}));
 return <motion.div className="absolute inset-0 z-[80] bg-black/70 flex items-center justify-center" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onDone}>
  {kind===0&&<div className="relative text-center">{parts.map((p,i)=><motion.span key={i} className="absolute left-1/2 top-1/2 w-2 h-2 rounded-full" style={{background:p.c}} initial={{x:0,y:0,opacity:1}} animate={{x:Math.cos(p.a)*p.d,y:Math.sin(p.a)*p.d,opacity:0}} transition={{duration:1.3,delay:.3}}/>)}
   <svg width="170" height="170"><circle cx="85" cy="85" r="72" stroke="#222" strokeWidth="12" fill="none"/><motion.circle cx="85" cy="85" r="72" stroke={Y} strokeWidth="12" fill="none" strokeLinecap="round" strokeDasharray={452} initial={{strokeDashoffset:452}} animate={{strokeDashoffset:0}} transition={{duration:1.1}} transform="rotate(-90 85 85)"/></svg>
   <div className="absolute inset-0 flex flex-col items-center justify-center"><motion.div initial={{scale:.4}} animate={{scale:[.4,1.3,1]}} transition={{delay:1}} className="text-4xl font-black" style={{color:Y}}>£200</motion.div><div className="text-xs text-neutral-300">daily goal smashed</div></div></div>}
  {kind===1&&<motion.div initial={{y:200,rotate:-6,opacity:0}} animate={{y:0,rotate:0,opacity:1}} transition={{type:"spring",damping:12}} className="w-[300px] rounded-3xl bg-[#0b0d12] p-5 text-center" style={{boxShadow:`0 0 50px ${P}99`,border:`1px solid ${P}`}}>
   <div className="text-3xl">{[0,1,2,3,4].map(i=><motion.span key={i} initial={{scale:0}} animate={{scale:[0,1.6,1]}} transition={{delay:.3+i*.12}} className="text-yellow-300 inline-block">★</motion.span>)}</div>
   <div className="mt-2 text-sm text-white">"Dave took the bus lane down Whitehall and got us there 6 minutes early. Legend."</div>
   <div className="mt-2 text-xs text-neutral-400">Testa</div>
   <div className="mt-3 flex justify-center gap-1">{[0,1,2,3,4,5].map(i=><motion.span key={i} initial={{y:-80,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:.9+i*.1,type:"spring"}}>🪙</motion.span>)}</div>
   <div className="font-black text-xl mt-1" style={{color:Y}}>+£4.00 tip cleared</div></motion.div>}
  {kind===2&&<div className="relative text-center">{[1,2,3].map(i=><motion.div key={i} className="absolute left-1/2 top-1/2 rounded-full border-2" style={{borderColor:G,width:20,height:20,marginLeft:-10,marginTop:-10}} initial={{scale:.5,opacity:.9}} animate={{scale:12*i/2+4,opacity:0}} transition={{duration:1.4,delay:i*.25}}/>)}
   <motion.div initial={{scale:3,rotate:-40,opacity:0}} animate={{scale:1,rotate:0,opacity:1}} transition={{type:"spring",damping:8,delay:.2}} className="text-8xl">🌟</motion.div>
   <div className="mt-2 text-xs tracking-[.2em]" style={{color:G}}>BADGE UNLOCKED</div><div className="text-2xl font-black text-white">Five-Star Streak</div><div className="text-sm text-neutral-300">12 in a row. Rider tips up 18% for streak drivers.</div></div>}
  <div className="absolute bottom-8 text-[11px] text-neutral-500">tap to dismiss</div></motion.div>}
export default function DriverApp(){
 const [tab,setTab]=useState("Home");const [on,setOn]=useState(false);const [earn,setEarn]=useState(128);const [xp,setXp]=useState(1840);const [cel,setCel]=useState<number|null>(null);
 const [filt,setFilt]=useState<"all"|"app"|"meter">("all");const [sel,setSel]=useState<[number,number]|null>(null);
 const [block,setBlock]=useState<Set<string>>(new Set(["0-1","1-1","2-1","3-1","0-3","1-3","2-3","3-3","4-3","5-0","5-1","5-2","6-0","6-1","6-2","6-3","6-4"]));
 const [goal,setGoal]=useState(900);const [redeem,setRedeem]=useState<number[]>([]);const [note,setNote]=useState(0);
 const fire=(k:number)=>{setCel(k);try{navigator.vibrate?.(k===1?[30,40,30,40,90]:k===0?[60,40,120]:[20,30,200])}catch{}};
 const f=(v:number)=>Math.round(v*(filt==="all"?1:filt==="app"?APP_SHARE:1-APP_SHARE));
 const dayTot=Y0.map(r=>r.reduce((a,b)=>a+b,0)*1.6);
 // Life Sync: choose best unblocked slots (3h each) until weekly goal met
 const plan=useMemo(()=>{const cells:{d:number;b:number;y:number}[]=[];Y0.forEach((r,d)=>r.forEach((y,b)=>{if(b<6&&!block.has(d+"-"+b))cells.push({d,b,y})}));
  cells.sort((a,b)=>b.y-a.y);let tot=0;const pick=new Set<string>();for(const c of cells){if(tot>=goal)break;pick.add(c.d+"-"+c.b);tot+=c.y*3}return{pick,tot,hrs:pick.size*3}},[block,goal]);
 const toggle=(d:number,b:number)=>setBlock(s=>{const n=new Set(s);const k=d+"-"+b;n.has(k)?n.delete(k):n.add(k);return n});
 const NOTES=["Your shift ends at 15:00 for school pickup. Tonight is yours. Tomorrow's game plan: 06-09 at King's Cross, forecast £26/hr.","Quiet one coming at 18:00 - and you blocked it for family. We'll hold your streak. Back on when you're ready.","You're £28 from today's goal. Soho clears out at 22:30 (forecast £52/hr). Your roster says you're free - your call, no pressure."];
 const lvl=Math.floor(xp/500)+1;
 const T=({k}:{k:string})=><button onClick={()=>setTab(k)} className={`flex-1 py-3 text-xs font-bold ${tab===k?"text-pink-400":"text-neutral-500"}`}>{({Home:"🏠",Earnings:"📈",Strategy:"🗺️",Garage:"🛠️"} as any)[k]}<div>{k}</div></button>;
 return <div className="w-full flex justify-center bg-black" style={{height:"100dvh"}}><div className="relative w-full max-w-[430px] h-full bg-[#07080c] text-white flex flex-col overflow-hidden" style={{fontFamily:"ui-rounded,system-ui,sans-serif"}}>
  <div className="px-4 pt-4 pb-2 flex items-center justify-between"><div><div className="text-[10px] tracking-[.2em]" style={{color:P}}>BLACK CAB · DRIVER TERMINAL</div><div className="font-black text-lg">Dave's Command Center</div></div><button onClick={()=>setOn(!on)} className="rounded-full px-4 py-2 text-sm font-black" style={{background:on?G:"#222",color:on?"#000":"#aaa",boxShadow:on?`0 0 18px ${G}88`:"none"}}>{on?"● ONLINE":"GO ONLINE"}</button></div>
  <div className="px-4 pb-2"><div className="inline-flex rounded-full bg-white/10 text-xs font-bold p-0.5"><Link href="/" className="px-3 py-1.5 text-neutral-400">Rider</Link><span className="rounded-full px-3 py-1.5 text-black" style={{background:P}}>Driver</span></div></div>
  <div className="flex-1 overflow-y-auto px-4 pb-3 space-y-3">
  {tab==="Home"&&<>
   <div className="rounded-3xl p-4 flex items-center gap-4" style={{background:"linear-gradient(135deg,#1a0a18,#0b0d12)",border:`1px solid ${P}55`}}>
    <svg width="96" height="96" viewBox="0 0 96 96"><circle cx="48" cy="48" r="40" stroke="#222" strokeWidth="9" fill="none"/><circle cx="48" cy="48" r="40" stroke={P} strokeWidth="9" fill="none" strokeLinecap="round" strokeDasharray={251} strokeDashoffset={251*(1-Math.min(1,earn/200))} transform="rotate(-90 48 48)" style={{filter:`drop-shadow(0 0 6px ${P})`}}/><text x="48" y="52" textAnchor="middle" fill="#fff" fontWeight="900" fontSize="18">£{earn}</text></svg>
    <div className="flex-1"><div className="text-xs text-neutral-400">Today vs £200 goal</div><div className="font-black text-xl">{earn>=200?"Goal hit":`£${200-earn} to go`}</div><div className="text-[11px] text-neutral-400">🔥 11 day streak · Level {lvl} · {xp} XP</div><div className="mt-1 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full" style={{width:`${(xp%500)/5}%`,background:`linear-gradient(90deg,${P},${Y})`}}/></div></div></div>
   <div className="rounded-3xl overflow-hidden relative h-40" style={{background:"radial-gradient(circle at 30% 40%,#ff2bd655,transparent 35%),radial-gradient(circle at 70% 60%,#34d39955,transparent 30%),radial-gradient(circle at 55% 25%,#facc1555,transparent 25%),#0b0d12",border:"1px solid #ffffff18"}}>
    {[["Soho",28,36,P],["King's X",58,20,Y],["Heathrow",78,66,G]].map(([n,x,y,c]:any)=><div key={n} className="absolute text-[10px] font-bold" style={{left:`${x}%`,top:`${y}%`,color:c}}><span className="inline-block w-3 h-3 rounded-full mr-1 animate-pulse" style={{background:c,boxShadow:`0 0 12px ${c}`}}/>{n}</div>)}
    <div className="absolute bottom-2 left-3 text-[11px] text-neutral-300">Live demand · simulated heat. {on?"You are visible to riders.":"Go online to receive jobs."}</div></div>
   <div className="grid grid-cols-3 gap-2"><button onClick={()=>{setEarn(e=>e+72);setXp(x=>x+40);fire(0)}} className="rounded-2xl bg-white/10 p-3 text-xs font-bold">🎯<div>Hit goal</div></button><button onClick={()=>{setEarn(e=>e+14);setXp(x=>x+25);fire(1)}} className="rounded-2xl bg-white/10 p-3 text-xs font-bold">⭐<div>5★ + tip</div></button><button onClick={()=>{setXp(x=>x+100);fire(2)}} className="rounded-2xl bg-white/10 p-3 text-xs font-bold">🏅<div>Badge</div></button></div>
   <div className="rounded-3xl bg-white/5 p-4"><div className="font-black mb-2">Compliment wall</div><div className="flex flex-wrap gap-1.5">{COMPS.map(c=><span key={c.t} className="text-[11px] rounded-full px-2.5 py-1" style={{background:"#ff2bd622",border:`1px solid ${P}55`}}>{c.t} <b style={{color:P}}>×{c.c}</b></span>)}</div>
    <div className="mt-3 space-y-2">{REVIEWS.map((r,i)=><div key={i} className="rounded-xl bg-black/40 p-2 text-xs"><span className="text-yellow-300">{"★".repeat(r.s)}</span> <b>{r.n}</b>{r.tip?<span className="float-right" style={{color:Y}}>+£{r.tip} tip</span>:null}<div className="text-neutral-300 mt-0.5">{r.t}</div></div>)}</div></div>
   <div className="rounded-3xl bg-white/5 p-4"><div className="font-black mb-2">Badges</div>{BADGES.map(b=><div key={b.n} className="flex items-center gap-3 mb-2"><div className="text-2xl w-9 text-center">{b.e}</div><div className="flex-1"><div className="text-sm font-bold">{b.n}{b.p>=b.t&&<span className="ml-1 text-[10px]" style={{color:G}}>EARNED</span>}</div><div className="text-[10px] text-neutral-400">{b.d}</div><div className="h-1.5 rounded-full bg-white/10 mt-1"><div className="h-full rounded-full" style={{width:`${Math.min(100,b.p/b.t*100)}%`,background:b.p>=b.t?G:P}}/></div></div><div className="text-[10px] text-neutral-400">{Math.min(b.p,b.t)}/{b.t}</div></div>)}</div>
   <div className="rounded-3xl bg-white/5 p-4"><div className="font-black mb-1">Nudges that respect your roster</div><div className="text-[11px] text-neutral-400 mb-2">Tap to preview the next push</div><button onClick={()=>setNote((note+1)%3)} className="w-full text-left rounded-2xl p-3 text-sm" style={{background:"#0b0d12",border:`1px solid ${P}44`}}><div className="text-[10px] text-neutral-500">DRIVER TERMINAL · now</div>{NOTES[note]}</button></div></>}
  {tab==="Earnings"&&<>
   <div className="flex gap-2">{(["all","app","meter"] as const).map(k=><button key={k} onClick={()=>setFilt(k)} className="flex-1 rounded-full py-2 text-xs font-bold" style={{background:filt===k?P:"#1a1a22",color:filt===k?"#000":"#aaa"}}>{k==="all"?"All fares":k==="app"?"App fares":"Meter fares"}</button>)}</div>
   <div className="rounded-3xl bg-white/5 p-4"><div className="text-xs text-neutral-400">This week</div><div className="text-4xl font-black" style={{color:Y}}>£{f(dayTot.reduce((a,b)=>a+b,0)).toLocaleString()}</div><div className="mt-3 flex items-end gap-2 h-28">{dayTot.map((v,i)=><button key={i} onClick={()=>setSel([i,sel?.[1]??4])} className="flex-1 flex flex-col items-center justify-end h-full"><motion.div animate={{height:`${f(v)/dayTot.reduce((a,b)=>Math.max(a,b))*100}%`}} className="w-full rounded-t-lg" style={{background:sel?.[0]===i?P:"#ff2bd688",boxShadow:sel?.[0]===i?`0 0 14px ${P}`:"none"}}/><span className="text-[10px] text-neutral-400 mt-1">{DAYS[i]}</span></button>)}</div></div>
   <div className="rounded-3xl bg-white/5 p-4"><div className="font-black mb-1">Yield heatmap</div><div className="text-[11px] text-neutral-400 mb-2">£/hr history. White ring = where you are today.</div>
    <div className="grid" style={{gridTemplateColumns:"34px repeat(7,1fr)",gap:3}}><div/>{DAYS.map(d=><div key={d} className="text-[10px] text-center text-neutral-400">{d}</div>)}
    {BANDS.map((b,bi)=><>{<div key={"l"+bi} className="text-[9px] text-neutral-500 flex items-center">{b}</div>}{DAYS.map((_,di)=><button key={di+"-"+bi} onClick={()=>setSel([di,bi])} className="h-8 rounded-md" style={{background:col(f(Y0[di][bi])),outline:di===4&&bi===4?"2px solid #fff":sel?.[0]===di&&sel?.[1]===bi?`2px solid ${Y}`:"none"}}/>)}</>)}</div>
    {sel&&<div className="mt-3 rounded-xl bg-black/50 p-3 text-sm"><b>{DAYS[sel[0]]} {BANDS[sel[1]]}</b>: <span style={{color:Y}}>£{f(Y0[sel[0]][sel[1]])}/hr</span><div className="text-[11px] text-neutral-400">{filt==="all"?"App ":""}{filt!=="meter"?`fares ${Math.round(APP_SHARE*100)}%`:""}{filt==="all"?" · ":""}{filt!=="app"?`meter ${Math.round((1-APP_SHARE)*100)}%`:""} · {Y0[sel[0]][sel[1]]>40?"Peak window. Riders pay for the Knowledge here.":"Steady. Good for a school run either side."}</div></div>}</div>
   <div className="rounded-3xl p-4 text-sm" style={{background:"#0b0d12",border:`1px solid ${G}55`}}><b style={{color:G}}>You keep 100% of every fare.</b> Subscription £29/wk flat, no commission. FreeNow-style 20% would have cost you <b>£{Math.round(dayTot.reduce((a,b)=>a+b,0)*0.2)}</b> this week (illustrative).</div></>}
  {tab==="Strategy"&&<>
   <div className="rounded-3xl bg-white/5 p-4"><div className="flex justify-between items-center"><div className="font-black">Life Sync roster</div><div className="text-[11px] text-neutral-400">tap slots to block</div></div>
    <div className="grid mt-2" style={{gridTemplateColumns:"34px repeat(7,1fr)",gap:3}}><div/>{DAYS.map(d=><div key={d} className="text-[10px] text-center text-neutral-400">{d}</div>)}
    {BANDS.slice(0,6).map((b,bi)=><>{<div key={"l"+bi} className="text-[9px] text-neutral-500 flex items-center">{b}</div>}{DAYS.map((_,di)=>{const k=di+"-"+bi,bl=block.has(k),pk=plan.pick.has(k);return <button key={k} onClick={()=>toggle(di,bi)} className="h-8 rounded-md text-[10px]" style={{background:bl?"#7c3aed55":pk?`${P}`:"#1a1a22",boxShadow:pk?`0 0 10px ${P}`:"none",border:bl?"1px dashed #a78bfa":"none"}}>{bl?"👨‍👩‍👧":pk?"£":""}</button>})}</>)}</div>
    <div className="mt-2 flex gap-3 text-[10px] text-neutral-400"><span>👨‍👩‍👧 blocked</span><span style={{color:P}}>■ AI driving window</span></div></div>
   <div className="rounded-3xl p-4" style={{background:"linear-gradient(135deg,#1a0a18,#0b0d12)",border:`1px solid ${P}55`}}><div className="flex items-center justify-between"><div className="text-xs text-neutral-400">Weekly goal</div><div className="flex items-center gap-2"><button onClick={()=>setGoal(g=>Math.max(300,g-100))} className="w-7 h-7 rounded-full bg-white/10">-</button><b>£{goal}</b><button onClick={()=>setGoal(g=>g+100)} className="w-7 h-7 rounded-full bg-white/10">+</button></div></div>
    <div className="mt-2 text-sm">Recalculated around your blocks: <b style={{color:P}}>{plan.hrs} hrs</b> projects <b style={{color:Y}}>£{Math.round(plan.tot)}</b> {plan.tot>=goal?<span style={{color:G}}>goal reachable</span>:<span className="text-orange-400">short by £{Math.round(goal-plan.tot)}. Free a slot or lower the goal.</span>}</div></div>
   <div className="rounded-3xl bg-white/5 p-4"><div className="font-black mb-2">Where to drive (forecast £/hr)</div>{ZONES.map(z=><div key={z.n} className="flex items-center gap-2 mb-2 text-sm"><div className="w-28 text-xs font-bold">{z.n}</div><div className="flex-1 h-2 rounded-full bg-white/10"><div className="h-full rounded-full" style={{width:`${z.y/60*100}%`,background:`linear-gradient(90deg,${P},${Y})`}}/></div><div className="w-10 text-right text-xs" style={{color:Y}}>£{z.y}</div></div>)}<div className="text-[10px] text-neutral-500">Forecast is a simulated model, not a live prediction.</div></div></>}
  {tab==="Garage"&&<>
   <div className="rounded-3xl p-4" style={{background:"linear-gradient(135deg,#3b2a05,#0b0d12)",border:`1px solid ${Y}66`}}><div className="text-[10px] tracking-[.2em]" style={{color:Y}}>THE GARAGE · GOLD MEMBER</div><div className="font-black text-xl">Perks that pay for the cab</div><div className="text-[11px] text-neutral-300">Saved £312 this year with Garage deals (simulated). Next tier: Platinum at {2500-xp>0?2500-xp:0} XP.</div></div>
   {DEALS.map((d,i)=><div key={d.n} className={`rounded-3xl p-4 bg-gradient-to-br ${d.g}`} style={{border:`1px solid ${d.a}66`,boxShadow:`0 0 20px ${d.a}22`}}><div className="flex items-start gap-3"><div className="text-3xl">{d.e}</div><div className="flex-1"><div className="font-black">{d.n}</div><div className="text-[11px] text-neutral-300">📍 {d.d}</div><div className="mt-1 text-sm font-bold" style={{color:d.a}}>{d.o}</div></div></div>
    <button onClick={()=>setRedeem(r=>r.includes(i)?r:[...r,i])} className="mt-3 w-full rounded-xl py-2 text-sm font-black" style={{background:redeem.includes(i)?"#ffffff22":d.a,color:redeem.includes(i)?"#fff":"#000"}}>{redeem.includes(i)?`Code TX-${1000+i*37} · show at kiosk`:"Claim member deal"}</button></div>)}</>}
  </div>
  <div className="flex border-t border-white/10 bg-[#07080c]">{["Home","Earnings","Strategy","Garage"].map(k=><T key={k} k={k}/>)}</div>
  <AnimatePresence>{cel!==null&&<Burst kind={cel} onDone={()=>setCel(null)}/>}</AnimatePresence>
 </div></div>}
